[package]
name = "nu-source"
version = "0.12.0"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "A source string characterizer for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
derive-new = "0.5.8"
getset = "0.0.9"
language-reporting = "0.4.0"
termcolor = "1.0.5"
pretty = "0.5.2"

[build-dependencies]
nu-build = { version = "0.12.0", path = "../nu-build" }
