[package]
authors = ["The Nu Project Contributors"]
description = "A source string characterizer for Nushell"
edition = "2018"
license = "MIT"
name = "nu-source"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
derive-new = "0.5.8"
getset = "0.1.1"
pretty = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
termcolor = "1.1.2"

[build-dependencies]
