[package]
name = "nu-source"
version = "0.14.1"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "A source string characterizer for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
derive-new = "0.5.8"
getset = "0.1.0"
language-reporting = "0.4.0"
termcolor = "1.1.0"
pretty = "0.5.2"

[build-dependencies]
nu-build = { version = "0.14.1", path = "../nu-build" }
