[package]
authors = ["The Nushell Project Developers"]
description = "Functionality for running Nushell plugins from a Nushell engine"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-plugin-engine"
edition = "2024"
license = "MIT"
name = "nu-plugin-engine"
version = "0.108.1"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
nu-engine = { path = "../nu-engine", version = "0.108.1" }
nu-protocol = { path = "../nu-protocol", version = "0.108.1" }
nu-system = { path = "../nu-system", version = "0.108.1" }
nu-plugin-protocol = { path = "../nu-plugin-protocol", version = "0.108.1" }
nu-plugin-core = { path = "../nu-plugin-core", version = "0.108.1", default-features = false }
nu-utils = { path = "../nu-utils", version = "0.108.1" }

serde = { workspace = true }
log = { workspace = true }

[dev-dependencies]
typetag = "0.2"

[features]
default = ["local-socket"]
local-socket = ["nu-plugin-core/local-socket"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  # For setting process creation flags
  "Win32_System_Threading",
] }
