[package]
authors = ["The Nushell Project Developers"]
description = "A converter plugin to the bson format for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_to_bson"
version = "0.71.1"

[lib]
doctest = false

[dependencies]
bson = { version = "2.0.1", features = [ "chrono-0_4" ] }
nu-errors = { path="../nu-errors", version = "0.71.1" }
nu-plugin = { path="../nu-plugin", version = "0.71.1" }
nu-protocol = { path="../nu-protocol", version = "0.71.1" }
nu-source = { path="../nu-source", version = "0.71.1" }
num-traits = "0.2.14"

[features]
dataframe = ["nu-protocol/dataframe"]

[build-dependencies]
