[package]
authors = ["The Nu Project Contributors"]
description = "A binary viewer plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_binaryview"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
crossterm = "0.19"
image = { version = "0.22.4", default_features = false, features = ["png_codec", "jpeg"] }
neso = "0.5.0"
nu-errors = { path = "../nu-errors", version = "0.27.1" }
nu-plugin = { path = "../nu-plugin", version = "0.27.1" }
nu-protocol = { path = "../nu-protocol", version = "0.27.1" }
nu-source = { path = "../nu-source", version = "0.27.1" }
nu-ansi-term = { version = "0.27.1", path = "../nu-ansi-term" }
pretty-hex = "0.2.1"
rawkey = "0.1.3"

[build-dependencies]
