[package]
authors = ["The Nu Project Contributors"]
description = "A binary viewer plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_binaryview"
version = "0.39.0"

[lib]
doctest = false

[dependencies]
crossterm = "0.19"
image = { version = "0.23.14", default_features = false, features = ["png", "jpeg"] }
neso = "0.5.0"
nu-errors = { path="../nu-errors", version = "0.39.0" }
nu-plugin = { path="../nu-plugin", version = "0.39.0" }
nu-protocol = { path="../nu-protocol", version = "0.39.0" }
nu-source = { path="../nu-source", version = "0.39.0" }
nu-ansi-term = { version = "0.39.0", path="../nu-ansi-term" }
nu-pretty-hex = { version = "0.39.0", path="../nu-pretty-hex" }
rawkey = "0.1.3"

[build-dependencies]
