image: Visual Studio 2017

environment:
  global:
    PROJECT_NAME: nushell
    RUST_BACKTRACE: 1
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly
      BITS: 64

install:
  - set PATH=C:\msys64\mingw%BITS%\bin;C:\msys64\usr\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  # Install rust
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  # Required for Racer autoconfiguration
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"


build: false

test_script:
  # compile #[cfg(not(test))] code
  - cargo build --verbose
  - cargo test --all --verbose

cache:
  - target -> Cargo.lock
  - C:\Users\appveyor\.cargo\registry -> Cargo.lock
