[package]
authors = ["The Nu Project Contributors"]
description = "A converter plugin to the bson format for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_from_sqlite"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
bigdecimal = "0.2.0"
nu-errors = { path = "../nu-errors", version = "0.27.1" }
nu-plugin = { path = "../nu-plugin", version = "0.27.1" }
nu-protocol = { path = "../nu-protocol", version = "0.27.1" }
nu-source = { path = "../nu-source", version = "0.27.1" }
nu-value-ext = { path = "../nu-value-ext", version = "0.27.1" }
num-traits = "0.2.14"
tempfile = "3.2.0"

[dependencies.rusqlite]
features = ["bundled", "blob"]
version = "0.24.2"

[build-dependencies]
