[package]
authors = ["The Nushell Project Developers"]
description = "A version incrementer plugin for Nushell"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu_plugin_inc"
edition = "2024"
license = "MIT"
name = "nu_plugin_inc"
version = "0.108.1"

[lib]
doctest = false
bench = false

[[bin]]
name = "nu_plugin_inc"
bench = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.108.1" }
nu-protocol = { path = "../nu-protocol", version = "0.108.1", features = ["plugin"] }

semver = "1.0"
