[package]
authors = ["The Nushell Project Developers"]
description = "A version incrementer plugin for Nushell"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu_plugin_inc"
edition = "2021"
license = "MIT"
name = "nu_plugin_inc"
version = "0.72.0"

[lib]
doctest = false

[dependencies]
nu-plugin = { path="../nu-plugin", version = "0.72.0" }
nu-protocol = { path="../nu-protocol", version = "0.72.0", features = ["plugin"]}

semver = "0.11.0"
