[package]
authors = ["The Nu Project Contributors"]
description = "A version incrementer plugin for Nushell"
edition = "2021"
license = "MIT"
name = "nu_plugin_inc"
version = "0.59.0"

[lib]
doctest = false

[dependencies]
nu-plugin = { path="../nu-plugin", version = "0.59.0" }
nu-protocol = { path="../nu-protocol", version = "0.59.0", features = ["plugin"]}

semver = "0.11.0"
