[package]
authors = ["The Nushell Project Developers"]
description = "A version incrementer plugin for Nushell"
edition = "2021"
license = "MIT"
name = "nu_plugin_inc"
version = "0.63.1"

[lib]
doctest = false

[dependencies]
nu-plugin = { path="../nu-plugin", version = "0.63.1" }
nu-protocol = { path="../nu-protocol", version = "0.63.1", features = ["plugin"]}

semver = "0.11.0"
