[package]
authors = ["The Nushell Project Developers"]
description = "Shared internal functionality to support Nushell plugins"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-plugin-core"
edition = "2024"
license = "MIT"
name = "nu-plugin-core"
version = "0.108.1"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
nu-protocol = { path = "../nu-protocol", version = "0.108.1" }
nu-plugin-protocol = { path = "../nu-plugin-protocol", version = "0.108.1", default-features = false }

rmp-serde = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
interprocess = { workspace = true, optional = true }

[features]
default = ["local-socket"]
local-socket = ["interprocess", "nu-plugin-protocol/local-socket"]

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }
