[package]
authors = ["The Nushell Project Developers"]
description = "Support for the NUON format."
repository = "https://github.com/nushell/nushell/tree/main/crates/nuon"
edition = "2024"
license = "MIT"
name = "nuon"
version = "0.108.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-parser = { path = "../nu-parser", version = "0.108.1" }
nu-protocol = { path = "../nu-protocol", version = "0.108.1", default-features = false }
nu-engine = { path = "../nu-engine", version = "0.108.1", default-features = false }
nu-utils = { path = "../nu-utils", version = "0.108.1", default-features = false }

[dev-dependencies]
chrono = { workspace = true }

[lints]
workspace = true
