[package]
authors = ["The Nushell Project Developers", "procs creators"]
description = "Nushell system querying"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-system"
name = "nu-system"
version = "0.88.1"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
bench = false

[dependencies]
libc = "0.2"
log = "0.4"
sysinfo = "0.29"

[target.'cfg(target_family = "unix")'.dependencies]
nix = { version = "0.27", default-features = false, features = ["fs", "term", "process", "signal"] }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
procfs = "0.16"

[target.'cfg(target_os = "macos")'.dependencies]
libproc = "0.14"
mach2 = "0.4"

[target.'cfg(target_os = "windows")'.dependencies]
chrono = { version = "0.4", default-features = false }
ntapi = "0.4"
once_cell = "1.18"
winapi = { version = "0.3", features = [
    "tlhelp32",
        "fileapi",
        "handleapi",
        "ifdef",
        "ioapiset",
        "minwindef",
        "pdh",
        "psapi",
        "synchapi",
        "sysinfoapi",
        "winbase",
        "winerror",
        "winioctl",
        "winnt",
        "oleauto",
        "wbemcli",
        "rpcdce",
        "combaseapi",
        "objidl",
        "powerbase",
        "netioapi",
        "lmcons",
        "lmaccess",
        "lmapibuf",
        "memoryapi",
        "shellapi",
        "std",
        "securitybaseapi",
        ] }
