[package]
authors = ["The Nu Project Contributors"]
description = "Extension traits for values in Nushell"
edition = "2018"
license = "MIT"
name = "nu-value-ext"
version = "0.24.2"

[lib]
doctest = false

[dependencies]
nu-errors = {path = "../nu-errors", version = "0.24.2"}
nu-protocol = {path = "../nu-protocol", version = "0.24.2"}
nu-source = {path = "../nu-source", version = "0.24.2"}

indexmap = {version = "1.6.0", features = ["serde-1"]}
itertools = "0.9.0"
num-traits = "0.2.12"
