[package]
authors = ["The Nu Project Contributors"]
description = "Nushell stream"
edition = "2018"
license = "MIT"
name = "nu-stream"
version = "0.27.1"

[dependencies]
nu-errors = { version = "0.27.1", path = "../nu-errors" }
nu-protocol = { version = "0.27.1", path = "../nu-protocol" }
nu-source = { version = "0.27.1", path = "../nu-source" }

futures = { version = "0.3.12", features = ["compat", "io-compat"] }

[features]
stable = []
trace = []
