[package]
authors = ["The Nu Project Contributors"]
description = "Nushell stream"
edition = "2018"
license = "MIT"
name = "nu-stream"
version = "0.37.1"

[dependencies]
nu-errors = { version = "0.37.1", path="../nu-errors" }
nu-protocol = { version = "0.37.1", path="../nu-protocol" }
nu-source = { version = "0.37.1", path="../nu-source" }

[features]
stable = []
