[package]
authors = ["The Nushell Project Developers"]
description = "A git status plugin for Nushell"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu_plugin_gstat"
edition = "2024"
license = "MIT"
name = "nu_plugin_gstat"
version = "0.105.2"

[lib]
doctest = false
bench = false

[[bin]]
name = "nu_plugin_gstat"
bench = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.105.2" }
nu-protocol = { path = "../nu-protocol", version = "0.105.2" }

git2 = "0.20"
