[package]
authors = ["The Nu Project Contributors"]
description = "A git status plugin for Nushell"
edition = "2021"
license = "MIT"
name = "nu_plugin_gstat"
version = "0.60.0"

[lib]
doctest = false

[dependencies]
nu-plugin = { path="../nu-plugin", version = "0.60.0" }
nu-protocol = { path="../nu-protocol", version = "0.60.0" }
nu-engine = { path="../nu-engine", version = "0.60.0" }

git2 = "0.13.24"
