[package]
name = "nu_plugin_sys"
version = "0.11.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andr√©s N. Robalino <andres@androbtech.com>"]
edition = "2018"
description = "A system info plugin for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.11.0" }
nu-protocol = { path = "../nu-protocol", version = "0.11.0" }
nu-source = { path = "../nu-source", version = "0.11.0" }
nu-errors = { path = "../nu-errors", version = "0.11.0" }

futures = { version = "0.3", features = ["compat", "io-compat"] }
battery = "0.7.5"
futures-util = "0.3.1"

[dependencies.heim]
version = "0.0.9"
default-features = false

features = ["host", "cpu", "memory", "disk", "net", "sensors", "runtime-polyfill"]

[build-dependencies]
nu-build = { version = "0.11.0", path = "../nu-build" }
