[package]
name = "nu_plugin_sys"
version = "0.14.1"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "A system info plugin for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.14.1" }
nu-protocol = { path = "../nu-protocol", version = "0.14.1" }
nu-source = { path = "../nu-source", version = "0.14.1" }
nu-errors = { path = "../nu-errors", version = "0.14.1" }

futures = { version = "0.3", features = ["compat", "io-compat"] }
battery = "0.7.5"
futures-util = "0.3.4"

[dependencies.heim]
version = "0.0.10"
default-features = false

features = ["host", "cpu", "memory", "disk", "net", "sensors", "runtime-polyfill"]

[build-dependencies]
nu-build = { version = "0.14.1", path = "../nu-build" }
