[package]
authors = ["The Nu Project Contributors"]
description = "A system info plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_sys"
version = "0.26.0"

[lib]
doctest = false

[dependencies]
nu-errors = { path = "../nu-errors", version = "0.26.0" }
nu-plugin = { path = "../nu-plugin", version = "0.26.0" }
nu-protocol = { path = "../nu-protocol", version = "0.26.0" }
nu-source = { path = "../nu-source", version = "0.26.0" }

futures = { version = "0.3.5", features = ["compat", "io-compat"] }
futures-util = "0.3.5"
num-bigint = "0.3.0"
sysinfo = "0.15.9"

[build-dependencies]
