[package]
authors = ["The Nu Project Contributors"]
description = "An S3 plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_s3"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
futures = { version = "0.3.12", features = ["compat", "io-compat"] }
nu-errors = { path = "../nu-errors", version = "0.27.1" }
nu-plugin = { path = "../nu-plugin", version = "0.27.1" }
nu-protocol = { path = "../nu-protocol", version = "0.27.1" }
nu-source = { path = "../nu-source", version = "0.27.1" }
s3handler = "0.6.3"

[build-dependencies]
