[package]
name = "nu_plugin_sum"
version = "0.8.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andr√©s N. Robalino <andres@androbtech.com>"]
edition = "2018"
description = "A simple summation plugin for Nushell"
license = "MIT"

[dependencies]
nu-plugin = { path = "../nu-plugin", version="0.8.0" }
nu-protocol = { path = "../nu-protocol", version = "0.8.0" }
nu-source = { path = "../nu-source", version = "0.8.0" }
nu-errors = { path = "../nu-errors", version = "0.8.0" }

[build-dependencies]
nu-build = { version = "0.8.0", path = "../nu-build" }
