[package]
authors = ["The Nu Project Contributors"]
description = "A set of query commands for Nushell"
edition = "2021"
license = "MIT"
name = "nu_plugin_query"
version = "0.60.0"

[lib]
doctest = false

[dependencies]
nu-plugin = { path="../nu-plugin", version = "0.60.0" }
nu-protocol = { path="../nu-protocol", version = "0.60.0" }
nu-engine = { path="../nu-engine", version = "0.60.0" }
gjson = "0.8.0"
scraper = "0.12.0"
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
