[package]
authors = ["The Nushell Project Developers"]
description = "A Nushell plugin to query JSON, XML, and various web data"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu_plugin_query"
edition = "2024"
license = "MIT"
name = "nu_plugin_query"
version = "0.105.2"

[lib]
doctest = false
bench = false

[[bin]]
name = "nu_plugin_query"
bench = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.105.2" }
nu-protocol = { path = "../nu-protocol", version = "0.105.2" }

gjson = "0.8"
scraper = { default-features = false, version = "0.23" }
sxd-document = "0.3"
sxd-xpath = "0.4"
webpage = { version = "2.0.1", features = ["serde"] }
serde_json.workspace = true
serde.workspace = true
