[package]
authors = ["The Nushell Project Developers"]
description = "A converter plugin to the bson format for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_from_sqlite"
version = "0.72.2"

[lib]
doctest = false

[dependencies]
bigdecimal = { package = "bigdecimal", version = "0.3.0", features = ["serde"] }
nu-errors = { path="../nu-errors", version = "0.72.2" }
nu-plugin = { path="../nu-plugin", version = "0.72.2" }
nu-protocol = { path="../nu-protocol", version = "0.72.2" }
nu-source = { path="../nu-source", version = "0.72.2" }
tempfile = "3.2.0"

[dependencies.rusqlite]
features = ["bundled", "blob"]
version = "0.26.1"

[build-dependencies]
