[package]
authors = ["The Nu Project Contributors"]
description = "query json files with gjson"
edition = "2018"
license = "MIT"
name = "nu_plugin_query_json"
version = "0.37.1"

[lib]
doctest = false

[dependencies]
gjson = "0.7.1"
nu-errors = { version = "0.37.1", path="../nu-errors" }
nu-plugin = { version = "0.37.1", path="../nu-plugin" }
nu-protocol = { version = "0.37.1", path="../nu-protocol" }
nu-source = { version = "0.37.1", path="../nu-source" }
