[package]
authors = ["The Nu Project Contributors"]
description = "query json files with gjson"
edition = "2018"
license = "MIT"
name = "nu_plugin_query_json"
version = "0.33.1"

[lib]
doctest = false

[dependencies]
gjson = "0.7.1"
nu-errors = { version="0.33.1", path="../nu-errors" }
nu-plugin = { version="0.33.1", path="../nu-plugin" }
nu-protocol = { version="0.33.1", path="../nu-protocol" }
nu-source = { version="0.33.1", path="../nu-source" }

[dev-dependencies]
nu-test-support = { path="../nu-test-support", version="0.33.1" }
