[package]
authors = ["The Nushell Project Developers"]
build = "build.rs"
description = "Nushell's core language commands"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-cmd-lang"
edition = "2021"
license = "MIT"
name = "nu-cmd-lang"
version = "0.95.1"

[lib]
bench = false

[dependencies]
nu-engine = { path = "../nu-engine", version = "0.95.1" }
nu-parser = { path = "../nu-parser", version = "0.95.1" }
nu-protocol = { path = "../nu-protocol", version = "0.95.1" }
nu-utils = { path = "../nu-utils", version = "0.95.1" }

itertools = { workspace = true }
shadow-rs = { version = "0.29", default-features = false }

[build-dependencies]
shadow-rs = { version = "0.29", default-features = false }

[features]
mimalloc = []
trash-support = []
sqlite = []
static-link-openssl = []
system-clipboard = []