[package]
authors = ["The Nushell Project Developers"]
build = "build.rs"
description = "Nushell's core language commands"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-cmd-lang"
edition = "2021"
license = "MIT"
name = "nu-cmd-lang"
version = "0.81.1"

[lib]
bench = false

[dependencies]
nu-color-config = { path = "../nu-color-config", version = "0.81.1" }
nu-engine = { path = "../nu-engine", version = "0.81.1" }
nu-parser = { path = "../nu-parser", version = "0.81.1" }
nu-protocol = { path = "../nu-protocol", version = "0.81.1"  }
nu-utils = { path = "../nu-utils", version = "0.81.1" }
nu-ansi-term = "0.48.0"

fancy-regex = "0.11"
itertools = "0.10"
shadow-rs = { version = "0.22", default-features = false }
ahash = "0.8.3"

[build-dependencies]
shadow-rs = { version = "0.22", default-features = false }

[features]
which-support = []
trash-support = []
sqlite = []
dataframe = []
static-link-openssl = []
wasi = []
extra = []
