[package]
authors = ["The Nushell Project Developers"]
build = "build.rs"
description = "Nushell's core language commands"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-cmd-lang"
edition = "2021"
license = "MIT"
name = "nu-cmd-lang"
version = "0.80.1"

[lib]
bench = false

[dependencies]
nu-color-config = { path = "../nu-color-config", version = "0.80.1" }
nu-engine = { path = "../nu-engine", version = "0.80.1" }
nu-parser = { path = "../nu-parser", version = "0.80.1" }
nu-protocol = { path = "../nu-protocol", version = "0.80.1"  }
nu-utils = { path = "../nu-utils", version = "0.80.1" }

nu-ansi-term = "0.47.0"

fancy-regex = "0.11.0"
itertools = "0.10.0"
log = "0.4.14"
shadow-rs = { version = "0.21.0", default-features = false }

[build-dependencies]
shadow-rs = { version = "0.21.0", default-features = false }

[dev-dependencies]
nu-test-support = { path="../nu-test-support", version = "0.80.1"  }
