[package]
authors = ["The Nu Project Contributors"]
description = "A process list plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_ps"
version = "0.18.1"

[lib]
doctest = false

[dependencies]
nu-errors = {path = "../nu-errors", version = "0.18.1"}
nu-plugin = {path = "../nu-plugin", version = "0.18.1"}
nu-protocol = {path = "../nu-protocol", version = "0.18.1"}
nu-source = {path = "../nu-source", version = "0.18.1"}

futures = {version = "0.3", features = ["compat", "io-compat"]}
futures-timer = "3.0.2"

[dependencies.heim]
default-features = false
features = ["process"]
version = "0.1.0-beta.3"

[build-dependencies]
