[package]
name = "nu_plugin_ps"
version = "0.11.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andr√©s N. Robalino <andres@androbtech.com>"]
edition = "2018"
description = "A process list plugin for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.11.0" }
nu-protocol = { path = "../nu-protocol", version = "0.11.0" }
nu-source = { path = "../nu-source", version = "0.11.0" }
nu-errors = { path = "../nu-errors", version = "0.11.0" }

futures = { version = "0.3", features = ["compat", "io-compat"] }
futures-timer = "3.0.1"
pin-utils = "0.1.0-alpha.4"

[dependencies.heim]
version = "0.0.9"
default-features = false
features = ["process", "runtime-polyfill"]

[build-dependencies]
nu-build = { version = "0.11.0", path = "../nu-build" }
