[package]
name = "nu_plugin_ps"
version = "0.8.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andr√©s N. Robalino <andres@androbtech.com>"]
edition = "2018"
description = "A process list plugin for Nushell"
license = "MIT"

[dependencies]
nu-plugin = { path = "../nu-plugin", version="0.8.0" }
nu-protocol = { path = "../nu-protocol", version = "0.8.0" }
nu-source = { path = "../nu-source", version = "0.8.0" }
nu-errors = { path = "../nu-errors", version = "0.8.0" }

futures-preview = { version = "=0.3.0-alpha.19", features = ["compat", "io-compat"] }
heim = "0.0.9"
futures-timer = "1.0.3"
pin-utils = "0.1.0-alpha.4"
futures-util = "0.3.1"

[build-dependencies]
nu-build = { version = "0.8.0", path = "../nu-build" }
