[package]
authors = ["The Nu Project Contributors"]
description = "CLI for nushell"
edition = "2018"
license = "MIT"
name = "nu-data"
version = "0.24.2"

[lib]
doctest = false

[dependencies]
ansi_term = "0.12.1"
bigdecimal = "0.2.0"
byte-unit = "4.0.9"

chrono = "0.4.15"
derive-new = "0.5.8"
directories = {version = "3.0.1", optional = true}
dirs = {version = "3.0.1", optional = true}
getset = "0.1.1"
indexmap = {version = "1.6.0", features = ["serde-1"]}
log = "0.4.11"
num-bigint = {version = "0.3.0", features = ["serde"]}
num-format = "0.4.0"
num-traits = "0.2.12"
parking_lot = "0.11.0"
query_interface = "0.3.5"
serde = {version = "1.0.115", features = ["derive"]}
toml = "0.5.6"

nu-errors = {version = "0.24.2", path = "../nu-errors"}
nu-protocol = {version = "0.24.2", path = "../nu-protocol"}
nu-source = {version = "0.24.2", path = "../nu-source"}
nu-table = {version = "0.24.2", path = "../nu-table"}
nu-test-support = {version = "0.24.2", path = "../nu-test-support"}
nu-value-ext = {version = "0.24.2", path = "../nu-value-ext"}

[target.'cfg(unix)'.dependencies]
users = "0.10.0"
