[package]
authors = ["The Nu Project Contributors"]
description = "CLI for nushell"
edition = "2018"
license = "MIT"
name = "nu-data"
version = "0.19.0"

[lib]
doctest = false

[dependencies]
ansi_term = "0.12.1"
bigdecimal = "0.1.2"
byte-unit = "3.1.3"

chrono = "0.4.15"
derive-new = "0.5.8"
directories = {version = "2.0.2", optional = true}
dirs = {version = "2.0.2", optional = true}
getset = "0.1.1"
indexmap = {version = "1.4.0", features = ["serde-1"]}
log = "0.4.8"
num-bigint = {version = "0.2.6", features = ["serde"]}
num-format = {version = "0.4", features = ["with-num-bigint"]}
num-traits = "0.2.11"
parking_lot = "0.11.0"
query_interface = "0.3.5"
serde = {version = "1.0.114", features = ["derive"]}
toml = "0.5.6"
umask = "1.0.0"

nu-errors = {version = "0.19.0", path = "../nu-errors"}
nu-protocol = {version = "0.19.0", path = "../nu-protocol"}
nu-source = {version = "0.19.0", path = "../nu-source"}
nu-table = {version = "0.19.0", path = "../nu-table"}
nu-value-ext = {version = "0.19.0", path = "../nu-value-ext"}

[target.'cfg(unix)'.dependencies]
users = "0.10.0"
