[package]
authors = ["The Nushell Project Developers"]
description = "Nushell table pager"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-explore"
edition = "2021"
license = "MIT"
name = "nu-explore"
version = "0.88.0"

[lib]
bench = false

[dependencies]
nu-ansi-term = "0.49.0"
nu-protocol = { path = "../nu-protocol", version = "0.88.0" }
nu-parser = { path = "../nu-parser", version = "0.88.0" }
nu-color-config = { path = "../nu-color-config", version = "0.88.0" }
nu-engine = { path = "../nu-engine", version = "0.88.0" }
nu-table = { path = "../nu-table", version = "0.88.0" }
nu-json = { path = "../nu-json", version = "0.88.0" }
nu-utils = { path = "../nu-utils", version = "0.88.0" }

terminal_size = "0.2"
strip-ansi-escapes = "0.2.0"
crossterm = "0.27"
ratatui = "0.23"
ansi-str = "0.8"
unicode-width = "0.1"
lscolors = { version = "0.15", default-features = false, features = ["nu-ansi-term"] }
