[package]
authors = ["The Nu Project Contributors"]
description = "A plugin to open files/URLs directly from Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_start"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
glob = "0.3.0"
nu-errors = { path = "../nu-errors", version = "0.27.1" }
nu-plugin = { path = "../nu-plugin", version = "0.27.1" }
nu-protocol = { path = "../nu-protocol", version = "0.27.1" }
nu-source = { path = "../nu-source", version = "0.27.1" }
open = "1.4.0"
url = "2.2.0"

[build-dependencies]
nu-errors = { version = "0.27.1", path = "../nu-errors" }
nu-source = { version = "0.27.1", path = "../nu-source" }
