[package]
name = "nu-errors"
version = "0.14.1"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "Core error subsystem for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-source = { path = "../nu-source", version = "0.14.1" }

ansi_term = "0.12.1"
bigdecimal = { version = "0.1.0", features = ["serde"] }
derive-new = "0.5.8"
language-reporting = "0.4.0"
num-bigint = { version = "0.2.6", features = ["serde"] }
num-traits = "0.2.11"
serde = { version = "1.0.106", features = ["derive"] }
getset = "0.1.0"

# implement conversions
serde_yaml = "0.8"
toml = "0.5.6"
serde_json = "1.0.51"
glob = "0.3.0"

[build-dependencies]
nu-build = { version = "0.14.1", path = "../nu-build" }
