[package]
authors = ["The Nushell Project Developers", "Christian Zangl <laktak@cdak.net>"]
description = "Fork of serde-hjson"
edition = "2021"
license = "MIT"
name = "nu-json"
version = "0.63.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
preserve_order = ["linked-hash-map", "linked-hash-map/serde_impl"]
default = ["preserve_order"]

[dependencies]
serde = "1.0"
num-traits = "0.2.14"
regex = "^1.0"
lazy_static = "1"
linked-hash-map = { version="0.5", optional=true }

[dev-dependencies]
nu-path = { path="../nu-path", version = "0.63.1" }
serde_json = "1.0"
