[package]
name = "nu_plugin_str"
version = "0.14.1"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "A string manipulation plugin for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.14.1" }
nu-protocol = { path = "../nu-protocol", version = "0.14.1" }
nu-source = { path = "../nu-source", version = "0.14.1" }
nu-errors = { path = "../nu-errors", version = "0.14.1" }
nu-value-ext = { path = "../nu-value-ext", version = "0.14.1" }
chrono = { version = "0.4.11", features = ["serde"] }

regex = "1"
num-bigint = "0.2.6"
bigdecimal = { version = "0.1.2", features = ["serde"] }

[build-dependencies]
nu-build = { version = "0.14.1", path = "../nu-build" }
