[package]
authors = ["The Nu Project Contributors"]
description = "Text viewer plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_textview"
version = "0.18.1"

[lib]
doctest = false

[dependencies]
nu-cli = {path = "../nu-cli", version = "0.18.1"}
nu-errors = {path = "../nu-errors", version = "0.18.1"}
nu-plugin = {path = "../nu-plugin", version = "0.18.1"}
nu-protocol = {path = "../nu-protocol", version = "0.18.1"}
nu-source = {path = "../nu-source", version = "0.18.1"}

ansi_term = "0.12.1"
bat = "0.15.4"
crossterm = "0.17.5"
syntect = {version = "4.2", default-features = false, features = ["default-fancy"]}
term_size = "0.3.2"
url = "2.1.1"

[build-dependencies]
