[package]
authors = ["The Nu Project Contributors"]
description = "Text viewer plugin for Nushell"
edition = "2018"
license = "MIT"
name = "nu_plugin_textview"
version = "0.27.1"

[lib]
doctest = false

[dependencies]
nu-data = { path = "../nu-data", version = "0.27.1" }
nu-errors = { path = "../nu-errors", version = "0.27.1" }
nu-plugin = { path = "../nu-plugin", version = "0.27.1" }
nu-protocol = { path = "../nu-protocol", version = "0.27.1" }
nu-source = { path = "../nu-source", version = "0.27.1" }
nu-ansi-term = { version = "0.27.1", path = "../nu-ansi-term" }

bat = { version = "0.17.1", features = ["regex-fancy", "paging"] }
term_size = "0.3.2"
url = "2.2.0"

[build-dependencies]
