[package]
name = "nu_plugin_textview"
version = "0.8.0"
authors = ["Yehuda Katz <wycats@gmail.com>", "Jonathan Turner <jonathan.d.turner@gmail.com>", "Andr√©s N. Robalino <andres@androbtech.com>"]
edition = "2018"
description = "Text viewer plugin for Nushell"
license = "MIT"

[dependencies]
nu-plugin = { path = "../nu-plugin", version="0.8.0" }
nu-protocol = { path = "../nu-protocol", version = "0.8.0" }
nu-source = { path = "../nu-source", version = "0.8.0" }
nu-errors = { path = "../nu-errors", version = "0.8.0" }

crossterm = "0.10.2"
syntect = "3.2.0"
onig_sys = "~69.1.0"
ansi_term = "0.12.1"
url = "2.1.0"

[build-dependencies]
nu-build = { version = "0.8.0", path = "../nu-build" }
