[package]
name = "nu_plugin_tree"
version = "0.16.0"
authors = ["The Nu Project Contributors"]
edition = "2018"
description = "Tree viewer plugin for Nushell"
license = "MIT"

[lib]
doctest = false

[dependencies]
nu-plugin = { path = "../nu-plugin", version = "0.16.0" }
nu-protocol = { path = "../nu-protocol", version = "0.16.0" }
nu-source = { path = "../nu-source", version = "0.16.0" }
nu-errors = { path = "../nu-errors", version = "0.16.0" }
ptree = {version = "0.2" }
derive-new = "0.5.8"

[build-dependencies]
nu-build = { version = "0.16.0", path = "../nu-build" }
