name: Submit Nushell package to Windows Package Manager Community Repository

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Specific tag name'
        required: true
        type: string

jobs:

  winget:
    name: Publish winget package
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Nushell.Nushell
          # Exclude *-msvc-full.msi Full release files
          installers-regex: 'msvc\.msi$' # Only standard .msi files
          version: ${{ inputs.tag_name || github.event.release.tag_name }}
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          token: ${{ secrets.NUSHELL_PAT }}
          fork-user: fdncred
