[package]
authors = ["The Nushell Project Developers"]
description = "Path handling library for Nushell"
edition = "2021"
license = "MIT"
name = "nu-path"
version = "0.63.1"

[dependencies]
dirs-next = "2.0.0"
dunce = "1.0.1"

[target.'cfg(target_os = "linux")'.dependencies]
pwd = "1.3.1"