[package]
authors = ["The Nushell Project Developers"]
description = "Path handling library for Nushell"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-path"
edition = "2024"
license = "MIT"
name = "nu-path"
version = "0.108.1"
exclude = ["/fuzz"]

[lib]
bench = false

[dependencies]
dirs = { workspace = true }
ref-cast = "1.0.23"

[target.'cfg(windows)'.dependencies]
omnipath = { workspace = true }

[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android")))'.dependencies]
pwd = { workspace = true }

[lints]
workspace = true
