[package]
authors = ["The Nushell Project Developers"]
description = "Path handling library for Nushell"
edition = "2021"
license = "MIT"
name = "nu-path"
version = "0.61.1"

[dependencies]
dirs-next = "2.0.0"
dunce = "1.0.1"

[target.'cfg(not(target_os = "windows"))'.dependencies]
pwd = "1.3.1"