[package]
authors = ["The Nu Project Contributors"]
description = "Nushell parser"
edition = "2018"
license = "MIT"
name = "nu-path"
version = "0.32.1"

[dependencies]
dirs-next = "2.0.0"
dunce = "1.0.1"
