[package]
authors = ["The Nushell Project Developers"]
description = "Nushell grid printing"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-term-grid"
edition = "2024"
license = "MIT"
name = "nu-term-grid"
version = "0.107.1"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
nu-utils = { path = "../nu-utils", version = "0.107.1", default-features = false }

unicode-width = { workspace = true }
