[package]
authors = ["The Nushell Project Developers"]
description = "Nushell grid printing"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-term-grid"
edition = "2021"
license = "MIT"
name = "nu-term-grid"
version = "0.96.1"

[lib]
bench = false

[dependencies]
nu-utils = { path = "../nu-utils", version = "0.96.1" }

unicode-width = { workspace = true }