[package]
authors = ["The Nushell Project Developers"]
description = "Nushell grid printing"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-term-grid"
edition = "2021"
license = "MIT"
name = "nu-term-grid"
version = "0.69.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "grid"
path = "src/main.rs"

[dependencies]
unicode-width = "0.1.9"
strip-ansi-escapes = "0.1.1"
